name: Kotodaman Notify Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bot
        env:
          EVENT_WEBHOOK_URL: ${{ secrets.EVENT_WEBHOOK_URL }}
          GACHA_WEBHOOK_URL: ${{ secrets.GACHA_WEBHOOK_URL }}
        run: python main.py
