name: Kotodaman Notify Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Packages
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        env:
          EVENT_WEBHOOK_URL: ${{ secrets.EVENT_WEBHOOK_URL }}
          GACHA_WEBHOOK_URL: ${{ secrets.GACHA_WEBHOOK_URL }}
          NOTICE_WEBHOOK_URL: ${{ secrets.NOTICE_WEBHOOK_URL }}
          MAINTENANCE_WEBHOOK_URL: ${{ secrets.MAINTENANCE_WEBHOOK_URL }}
        run: |
          python main.py

      - name: Commit JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add events.json seen_news.json

          git diff --cached --quiet || git commit -m "Update notify cache"

          git push